name: My First Workflow

on: push 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: echo "version=1.2.3" >> $GITHUB_OUTPUT

      - name: Use version
        run: echo "Deploying version ${{ steps.get_version.outputs.version }}"

      - name: Check cache
        id: cache_check
        run: echo "cache-hit=false" >> $GITHUB_OUTPUT

      - name: Install dependencies
        if: ${{ steps.cache_check.outputs.cache-hit != 'true' }}
        run: echo " npm install required"
      - name: checking github output
        run: echo ${{ steps.cache_check.outputs }}



